/* Generated By:JavaCC: Do not edit this line. RubyParser14Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RubyParser14Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int keyword_super = 1;
  /** RegularExpression Id. */
  int T = 2;
  /** RegularExpression Id. */
  int pipe = 6;
  /** RegularExpression Id. */
  int quote = 7;
  /** RegularExpression Id. */
  int apostr = 8;
  /** RegularExpression Id. */
  int backapostr = 9;
  /** RegularExpression Id. */
  int colon = 10;
  /** RegularExpression Id. */
  int equal = 11;
  /** RegularExpression Id. */
  int underline = 12;
  /** RegularExpression Id. */
  int plusequal = 13;
  /** RegularExpression Id. */
  int starequal = 14;
  /** RegularExpression Id. */
  int slashequal = 15;
  /** RegularExpression Id. */
  int percentequal = 16;
  /** RegularExpression Id. */
  int powerequal = 17;
  /** RegularExpression Id. */
  int minusequal = 18;
  /** RegularExpression Id. */
  int amperequal = 19;
  /** RegularExpression Id. */
  int andequal = 20;
  /** RegularExpression Id. */
  int pipeequal = 21;
  /** RegularExpression Id. */
  int orequal = 22;
  /** RegularExpression Id. */
  int lshiftequal = 23;
  /** RegularExpression Id. */
  int caretequal = 24;
  /** RegularExpression Id. */
  int equal2 = 25;
  /** RegularExpression Id. */
  int equal3 = 26;
  /** RegularExpression Id. */
  int lbrace = 27;
  /** RegularExpression Id. */
  int rbrace = 28;
  /** RegularExpression Id. */
  int at = 29;
  /** RegularExpression Id. */
  int dollar = 30;
  /** RegularExpression Id. */
  int plusat = 31;
  /** RegularExpression Id. */
  int minusat = 32;
  /** RegularExpression Id. */
  int lsqbracket = 33;
  /** RegularExpression Id. */
  int sqbrackets = 34;
  /** RegularExpression Id. */
  int sqbracketsequal = 35;
  /** RegularExpression Id. */
  int rsqbracket = 36;
  /** RegularExpression Id. */
  int lparen = 37;
  /** RegularExpression Id. */
  int rparen = 38;
  /** RegularExpression Id. */
  int comma = 39;
  /** RegularExpression Id. */
  int exclamation = 40;
  /** RegularExpression Id. */
  int question = 41;
  /** RegularExpression Id. */
  int exclamationequal = 42;
  /** RegularExpression Id. */
  int exclamationtilde = 43;
  /** RegularExpression Id. */
  int equaltilde = 44;
  /** RegularExpression Id. */
  int tilde = 45;
  /** RegularExpression Id. */
  int less = 46;
  /** RegularExpression Id. */
  int lshift = 47;
  /** RegularExpression Id. */
  int more = 48;
  /** RegularExpression Id. */
  int rshift = 49;
  /** RegularExpression Id. */
  int lessorequal = 50;
  /** RegularExpression Id. */
  int moreorequal = 51;
  /** RegularExpression Id. */
  int rshiftequal = 52;
  /** RegularExpression Id. */
  int lessequalmore = 53;
  /** RegularExpression Id. */
  int equalmore = 54;
  /** RegularExpression Id. */
  int caret = 55;
  /** RegularExpression Id. */
  int dot = 56;
  /** RegularExpression Id. */
  int dot2 = 57;
  /** RegularExpression Id. */
  int dot3 = 58;
  /** RegularExpression Id. */
  int plus = 59;
  /** RegularExpression Id. */
  int minus = 60;
  /** RegularExpression Id. */
  int star = 61;
  /** RegularExpression Id. */
  int power = 62;
  /** RegularExpression Id. */
  int slash = 63;
  /** RegularExpression Id. */
  int percent = 64;
  /** RegularExpression Id. */
  int amper = 65;
  /** RegularExpression Id. */
  int and = 66;
  /** RegularExpression Id. */
  int or = 67;
  /** RegularExpression Id. */
  int colon2 = 68;
  /** RegularExpression Id. */
  int keyword_do = 69;
  /** RegularExpression Id. */
  int keyword_self = 70;
  /** RegularExpression Id. */
  int keyword_then = 71;
  /** RegularExpression Id. */
  int keyword_ensure = 72;
  /** RegularExpression Id. */
  int keyword_defined = 73;
  /** RegularExpression Id. */
  int keyword_begin = 74;
  /** RegularExpression Id. */
  int keyword_case = 75;
  /** RegularExpression Id. */
  int keyword_for = 76;
  /** RegularExpression Id. */
  int keyword_class = 77;
  /** RegularExpression Id. */
  int keyword_end = 78;
  /** RegularExpression Id. */
  int keyword_numeric = 79;
  /** RegularExpression Id. */
  int keyword_BEGIN = 80;
  /** RegularExpression Id. */
  int keyword_END = 81;
  /** RegularExpression Id. */
  int keyword_undef = 82;
  /** RegularExpression Id. */
  int keyword_rescue = 83;
  /** RegularExpression Id. */
  int keyword_alias = 84;
  /** RegularExpression Id. */
  int keyword_else = 85;
  /** RegularExpression Id. */
  int keyword_if = 86;
  /** RegularExpression Id. */
  int keyword_in = 87;
  /** RegularExpression Id. */
  int keyword_elsif = 88;
  /** RegularExpression Id. */
  int keyword_while = 89;
  /** RegularExpression Id. */
  int keyword_module = 90;
  /** RegularExpression Id. */
  int keyword_def = 91;
  /** RegularExpression Id. */
  int keyword_when = 92;
  /** RegularExpression Id. */
  int keyword_unless = 93;
  /** RegularExpression Id. */
  int keyword_until = 94;
  /** RegularExpression Id. */
  int keyword_yield = 95;
  /** RegularExpression Id. */
  int keyword_nil = 96;
  /** RegularExpression Id. */
  int keyword_and = 97;
  /** RegularExpression Id. */
  int keyword_or = 98;
  /** RegularExpression Id. */
  int keyword_return = 99;
  /** RegularExpression Id. */
  int keyword_not = 100;
  /** RegularExpression Id. */
  int eps = 101;
  /** RegularExpression Id. */
  int letter = 102;
  /** RegularExpression Id. */
  int digit = 103;
  /** RegularExpression Id. */
  int symbol = 104;
  /** RegularExpression Id. */
  int Q = 105;
  /** RegularExpression Id. */
  int q = 106;
  /** RegularExpression Id. */
  int x = 107;
  /** RegularExpression Id. */
  int r = 108;
  /** RegularExpression Id. */
  int i = 109;
  /** RegularExpression Id. */
  int o = 110;
  /** RegularExpression Id. */
  int p = 111;
  /** RegularExpression Id. */
  int NUMBER = 112;
  /** RegularExpression Id. */
  int DIGITS = 113;
  /** RegularExpression Id. */
  int EOL = 114;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"super\"",
    "<T>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"|\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"`\"",
    "\":\"",
    "\"=\"",
    "\"_\"",
    "\"+=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"**=\"",
    "\"-=\"",
    "\"&=\"",
    "\"&&=\"",
    "\"|=\"",
    "\"||=\"",
    "\"<<=\"",
    "\"^=\"",
    "\"==\"",
    "\"===\"",
    "\"{\"",
    "\"}\"",
    "\"@\"",
    "\"$\"",
    "\"+@\"",
    "\"-@\"",
    "\"[\"",
    "\"[]\"",
    "\"[]=\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"!\"",
    "\"?\"",
    "\"!=\"",
    "\"!~\"",
    "\"=~\"",
    "\"~\"",
    "\"<\"",
    "\"<<\"",
    "\">\"",
    "\">>\"",
    "\"<=\"",
    "\">=\"",
    "\" >>=\"",
    "\"<=>\"",
    "\"=>\"",
    "\"^\"",
    "\".\"",
    "\"..\"",
    "\"...\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"**\"",
    "\"/\"",
    "\"%\"",
    "\"&\"",
    "\"&&\"",
    "\"||\"",
    "\"::\"",
    "\"do\"",
    "\"self\"",
    "\"then\"",
    "\"ensure\"",
    "\"defined?\"",
    "\"begin\"",
    "\"case\"",
    "\"for\"",
    "\"class\"",
    "\"end\"",
    "\"numeric\"",
    "\"BEGIN\"",
    "\"END\"",
    "\"undef\"",
    "\"rescue\"",
    "\"alias\"",
    "\"else\"",
    "\"if\"",
    "\"in\"",
    "\"elsif\"",
    "\"while\"",
    "\"module\"",
    "\"def\"",
    "\"when\"",
    "\"unless\"",
    "\"until\"",
    "\"yield\"",
    "\"nil\"",
    "\"and\"",
    "\"or\"",
    "\"return\"",
    "\"not\"",
    "\"\"",
    "<letter>",
    "<digit>",
    "<symbol>",
    "\"Q\"",
    "\"q\"",
    "\"x\"",
    "\"r\"",
    "\"i\"",
    "\"o\"",
    "\"p\"",
    "<NUMBER>",
    "<DIGITS>",
    "<EOL>",
  };

}
