/* Generated By:JavaCC: Do not edit this line. RubyParserReloadConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RubyParserReloadConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T = 3;
  /** RegularExpression Id. */
  int letter = 4;
  /** RegularExpression Id. */
  int quote = 5;
  /** RegularExpression Id. */
  int digit = 6;
  /** RegularExpression Id. */
  int pipe = 7;
  /** RegularExpression Id. */
  int backslash = 8;
  /** RegularExpression Id. */
  int apostr = 9;
  /** RegularExpression Id. */
  int backapostr = 10;
  /** RegularExpression Id. */
  int colon = 11;
  /** RegularExpression Id. */
  int number = 12;
  /** RegularExpression Id. */
  int equal = 13;
  /** RegularExpression Id. */
  int underscore = 14;
  /** RegularExpression Id. */
  int plusequal = 15;
  /** RegularExpression Id. */
  int starequal = 16;
  /** RegularExpression Id. */
  int slashequal = 17;
  /** RegularExpression Id. */
  int percentequal = 18;
  /** RegularExpression Id. */
  int powerequal = 19;
  /** RegularExpression Id. */
  int minusequal = 20;
  /** RegularExpression Id. */
  int amperequal = 21;
  /** RegularExpression Id. */
  int andequal = 22;
  /** RegularExpression Id. */
  int pipeequal = 23;
  /** RegularExpression Id. */
  int orequal = 24;
  /** RegularExpression Id. */
  int lshiftequal = 25;
  /** RegularExpression Id. */
  int caretequal = 26;
  /** RegularExpression Id. */
  int equal2 = 27;
  /** RegularExpression Id. */
  int equal3 = 28;
  /** RegularExpression Id. */
  int lbrace = 29;
  /** RegularExpression Id. */
  int rbrace = 30;
  /** RegularExpression Id. */
  int at = 31;
  /** RegularExpression Id. */
  int dollar = 32;
  /** RegularExpression Id. */
  int plusat = 33;
  /** RegularExpression Id. */
  int minusat = 34;
  /** RegularExpression Id. */
  int lsqbracket = 35;
  /** RegularExpression Id. */
  int sqbrackets = 36;
  /** RegularExpression Id. */
  int sqbracketsequal = 37;
  /** RegularExpression Id. */
  int rsqbracket = 38;
  /** RegularExpression Id. */
  int lparen = 39;
  /** RegularExpression Id. */
  int rparen = 40;
  /** RegularExpression Id. */
  int comma = 41;
  /** RegularExpression Id. */
  int exclamation = 42;
  /** RegularExpression Id. */
  int question = 43;
  /** RegularExpression Id. */
  int exclamationequal = 44;
  /** RegularExpression Id. */
  int exclamationtilde = 45;
  /** RegularExpression Id. */
  int equaltilde = 46;
  /** RegularExpression Id. */
  int tilde = 47;
  /** RegularExpression Id. */
  int less = 48;
  /** RegularExpression Id. */
  int lshift = 49;
  /** RegularExpression Id. */
  int more = 50;
  /** RegularExpression Id. */
  int rshift = 51;
  /** RegularExpression Id. */
  int lessorequal = 52;
  /** RegularExpression Id. */
  int moreorequal = 53;
  /** RegularExpression Id. */
  int rshiftequal = 54;
  /** RegularExpression Id. */
  int lessequalmore = 55;
  /** RegularExpression Id. */
  int equalmore = 56;
  /** RegularExpression Id. */
  int caret = 57;
  /** RegularExpression Id. */
  int dot = 58;
  /** RegularExpression Id. */
  int dot2 = 59;
  /** RegularExpression Id. */
  int dot3 = 60;
  /** RegularExpression Id. */
  int plus = 61;
  /** RegularExpression Id. */
  int minus = 62;
  /** RegularExpression Id. */
  int star = 63;
  /** RegularExpression Id. */
  int power = 64;
  /** RegularExpression Id. */
  int slash = 65;
  /** RegularExpression Id. */
  int percent = 66;
  /** RegularExpression Id. */
  int amper = 67;
  /** RegularExpression Id. */
  int and = 68;
  /** RegularExpression Id. */
  int or = 69;
  /** RegularExpression Id. */
  int colon2 = 70;
  /** RegularExpression Id. */
  int keyword_do = 71;
  /** RegularExpression Id. */
  int keyword_self = 72;
  /** RegularExpression Id. */
  int keyword_then = 73;
  /** RegularExpression Id. */
  int keyword_ensure = 74;
  /** RegularExpression Id. */
  int keyword_defined = 75;
  /** RegularExpression Id. */
  int keyword_begin = 76;
  /** RegularExpression Id. */
  int keyword_case = 77;
  /** RegularExpression Id. */
  int keyword_for = 78;
  /** RegularExpression Id. */
  int keyword_class = 79;
  /** RegularExpression Id. */
  int keyword_end = 80;
  /** RegularExpression Id. */
  int keyword_numeric = 81;
  /** RegularExpression Id. */
  int keyword_BEGIN = 82;
  /** RegularExpression Id. */
  int keyword_END = 83;
  /** RegularExpression Id. */
  int keyword_undef = 84;
  /** RegularExpression Id. */
  int keyword_rescue = 85;
  /** RegularExpression Id. */
  int keyword_alias = 86;
  /** RegularExpression Id. */
  int keyword_else = 87;
  /** RegularExpression Id. */
  int keyword_if = 88;
  /** RegularExpression Id. */
  int keyword_in = 89;
  /** RegularExpression Id. */
  int keyword_elsif = 90;
  /** RegularExpression Id. */
  int keyword_while = 91;
  /** RegularExpression Id. */
  int keyword_module = 92;
  /** RegularExpression Id. */
  int keyword_def = 93;
  /** RegularExpression Id. */
  int keyword_when = 94;
  /** RegularExpression Id. */
  int keyword_unless = 95;
  /** RegularExpression Id. */
  int keyword_until = 96;
  /** RegularExpression Id. */
  int keyword_yield = 97;
  /** RegularExpression Id. */
  int keyword_nil = 98;
  /** RegularExpression Id. */
  int keyword_and = 99;
  /** RegularExpression Id. */
  int keyword_or = 100;
  /** RegularExpression Id. */
  int keyword_return = 101;
  /** RegularExpression Id. */
  int keyword_not = 102;
  /** RegularExpression Id. */
  int keyword_super = 103;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<T>",
    "<letter>",
    "\"\\\"\"",
    "<digit>",
    "\"|\"",
    "\"\\\\\"",
    "\"\\\'\"",
    "\"`\"",
    "\":\"",
    "\"#\"",
    "\"=\"",
    "\"_\"",
    "\"+=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"**=\"",
    "\"-=\"",
    "\"&=\"",
    "\"&&=\"",
    "\"|=\"",
    "\"||=\"",
    "\"<<=\"",
    "\"^=\"",
    "\"==\"",
    "\"===\"",
    "\"{\"",
    "\"}\"",
    "\"@\"",
    "\"$\"",
    "\"+@\"",
    "\"-@\"",
    "\"[\"",
    "\"[]\"",
    "\"[]=\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"!\"",
    "\"?\"",
    "\"!=\"",
    "\"!~\"",
    "\"=~\"",
    "\"~\"",
    "\"<\"",
    "\"<<\"",
    "\">\"",
    "\">>\"",
    "\"<=\"",
    "\">=\"",
    "\" >>=\"",
    "\"<=>\"",
    "\"=>\"",
    "\"^\"",
    "\".\"",
    "\"..\"",
    "\"...\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"**\"",
    "\"/\"",
    "\"%\"",
    "\"&\"",
    "\"&&\"",
    "\"||\"",
    "\"::\"",
    "\"do\"",
    "\"self\"",
    "\"then\"",
    "\"ensure\"",
    "\"defined?\"",
    "\"begin\"",
    "\"case\"",
    "\"for\"",
    "\"class\"",
    "\"end\"",
    "\"numeric\"",
    "\"BEGIN\"",
    "\"END\"",
    "\"undef\"",
    "\"rescue\"",
    "\"alias\"",
    "\"else\"",
    "\"if\"",
    "\"in\"",
    "\"elsif\"",
    "\"while\"",
    "\"module\"",
    "\"def\"",
    "\"when\"",
    "\"unless\"",
    "\"until\"",
    "\"yield\"",
    "\"nil\"",
    "\"and\"",
    "\"or\"",
    "\"return\"",
    "\"not\"",
    "\"super\"",
  };

}
