/* Generated By:JavaCC: Do not edit this line. RubyParserReload2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RubyParserReload2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int underscore = 3;
  /** RegularExpression Id. */
  int quote = 4;
  /** RegularExpression Id. */
  int symbol = 5;
  /** RegularExpression Id. */
  int letter = 6;
  /** RegularExpression Id. */
  int digit = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"_\"",
    "\"\\\"\"",
    "<symbol>",
    "<letter>",
    "<digit>",
  };

}
