/* Generated By:JavaCC: Do not edit this line. RubyParser14TokenManager.java */
import java.io.StringReader;
import java.io.Reader;

/** Token Manager. */
public class RubyParser14TokenManager implements RubyParser14Constants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0, long active1, long active2)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x40L) != 0L || (active1 & 0x1800000L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 0;
            return 0;
         }
         if ((active0 & 0x1260000040000000L) != 0L)
            return 8;
         if ((active0 & 0x1f80L) != 0L || (active1 & 0xffffe7ff000L) != 0L || (active2 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 0;
            return 1;
         }
         return -1;
      case 1:
         if ((active1 & 0x1800000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 4;
               jjmatchedPos = 1;
            }
            return 0;
         }
         if ((active1 & 0xffffe7ff000L) != 0L || (active2 & 0x2000000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 4;
               jjmatchedPos = 1;
            }
            return 1;
         }
         return -1;
      case 2:
         if ((active1 & 0x1800000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 4;
               jjmatchedPos = 2;
            }
            return 0;
         }
         if ((active1 & 0xdff9e7fe000L) != 0L || (active2 & 0x2000000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 4;
               jjmatchedPos = 2;
            }
            return 1;
         }
         return -1;
      case 3:
         if ((active1 & 0x47b9e57e000L) != 0L || (active2 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 3;
            return 1;
         }
         if ((active1 & 0x800000L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 3;
            return 0;
         }
         return -1;
      case 4:
         if ((active1 & 0x4738e538000L) != 0L || (active2 & 0x2000000L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 4;
               jjmatchedPos = 4;
            }
            return 1;
         }
         if ((active1 & 0x800000L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 4;
               jjmatchedPos = 4;
            }
            return 0;
         }
         return -1;
      case 5:
         if ((active1 & 0x41204418000L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 5;
            return 1;
         }
         return -1;
      case 6:
         if ((active1 & 0x410000L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 6;
            return 1;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0, long active1, long active2)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1, active2), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 32:
         {
         jjmatchedKind = 1;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x800000000000000L, 0x0L, 0x0L);
      case 33:
         {
         jjmatchedKind = 47;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x6000000000008L, 0xffffe00000000000L, 0x1ffffffL);
      case 34:
         return jjStopAtPos(0, 15);
      case 36:
         return jjStopAtPos(0, 37);
      case 37:
         {
         jjmatchedKind = 71;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x800000L, 0x0L, 0x0L);
      case 38:
         {
         jjmatchedKind = 72;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0xc000000L, 0x200L, 0x0L);
      case 39:
         return jjStopAtPos(0, 16);
      case 40:
         return jjStopAtPos(0, 44);
      case 41:
         return jjStopAtPos(0, 45);
      case 42:
         {
         jjmatchedKind = 68;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x1200000L, 0x20L, 0x0L);
      case 43:
         {
         jjmatchedKind = 66;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x4000100000L, 0x0L, 0x0L);
      case 44:
         return jjStopAtPos(0, 46);
      case 45:
         {
         jjmatchedKind = 67;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x8002000000L, 0x0L, 0x0L);
      case 46:
         {
         jjmatchedKind = 63;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x0L, 0x3L, 0x0L);
      case 47:
         {
         jjmatchedKind = 70;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x400000L, 0x0L, 0x0L);
      case 58:
         {
         jjmatchedKind = 18;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800L, 0x0L);
      case 60:
         {
         jjmatchedKind = 53;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x1240000040000000L, 0x0L, 0x0L);
      case 61:
         {
         jjmatchedKind = 19;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x2008000300000000L, 0x0L, 0x0L);
      case 62:
         {
         jjmatchedKind = 55;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x500000000000000L, 0x0L, 0x0L);
      case 63:
         return jjStopAtPos(0, 48);
      case 64:
         return jjStopAtPos(0, 36);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800000L, 0x0L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1000000L, 0x0L);
      case 81:
         return jjStartNfaWithStates_0(0, 4, 0);
      case 91:
         {
         jjmatchedKind = 40;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x60000000000L, 0x0L, 0x0L);
      case 93:
         return jjStopAtPos(0, 43);
      case 94:
         {
         jjmatchedKind = 62;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x80000000L, 0x0L, 0x0L);
      case 96:
         return jjStopAtPos(0, 17);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x10008000000L, 0x0L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20000L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x140000L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400011000L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x90208000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80000L, 0x0L);
      case 105:
         {
         jjmatchedKind = 4;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x0L, 0x60000000L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200000000L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x88000400000L, 0x0L);
      case 111:
         {
         jjmatchedKind = 4;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20000000000L, 0x0L);
      case 112:
         return jjStartNfaWithStates_0(0, 4, 1);
      case 113:
         return jjStartNfaWithStates_0(0, 4, 1);
      case 114:
         {
         jjmatchedKind = 4;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x0L, 0x40004000000L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2000L, 0x2000000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4000L, 0x0L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x3002000000L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x900000000L, 0x0L);
      case 120:
         return jjStartNfaWithStates_0(0, 4, 1);
      case 121:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4000000000L, 0x0L);
      case 123:
         return jjStopAtPos(0, 34);
      case 124:
         {
         jjmatchedKind = 14;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x30000000L, 0x400L, 0x0L);
      case 125:
         return jjStopAtPos(0, 35);
      case 126:
         return jjStopAtPos(0, 52);
      default :
         return jjMoveNfa_0(2, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0, long active1, long active2)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1, active2);
      return 1;
   }
   switch(curChar)
   {
      case 33:
         return jjMoveStringLiteralDfa2_0(active0, 0x8L, active1, 0L, active2, 0L);
      case 38:
         if ((active1 & 0x200L) != 0L)
         {
            jjmatchedKind = 73;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000L, active1, 0L, active2, 0L);
      case 42:
         if ((active1 & 0x20L) != 0L)
         {
            jjmatchedKind = 69;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000L, active1, 0L, active2, 0L);
      case 46:
         if ((active1 & 0x1L) != 0L)
         {
            jjmatchedKind = 64;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x2L, active2, 0L);
      case 58:
         if ((active1 & 0x800L) != 0L)
            return jjStopAtPos(1, 75);
         break;
      case 60:
         if ((active0 & 0x40000000000000L) != 0L)
         {
            jjmatchedKind = 54;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L, active1, 0L, active2, 0L);
      case 61:
         if ((active0 & 0x100000L) != 0L)
            return jjStopAtPos(1, 20);
         else if ((active0 & 0x200000L) != 0L)
            return jjStopAtPos(1, 21);
         else if ((active0 & 0x400000L) != 0L)
            return jjStopAtPos(1, 22);
         else if ((active0 & 0x800000L) != 0L)
            return jjStopAtPos(1, 23);
         else if ((active0 & 0x2000000L) != 0L)
            return jjStopAtPos(1, 25);
         else if ((active0 & 0x4000000L) != 0L)
            return jjStopAtPos(1, 26);
         else if ((active0 & 0x10000000L) != 0L)
            return jjStopAtPos(1, 28);
         else if ((active0 & 0x80000000L) != 0L)
            return jjStopAtPos(1, 31);
         else if ((active0 & 0x100000000L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x2000000000000L) != 0L)
            return jjStopAtPos(1, 49);
         else if ((active0 & 0x200000000000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x400000000000000L) != 0L)
            return jjStopAtPos(1, 58);
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000200000000L, active1, 0L, active2, 0L);
      case 62:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStopAtPos(1, 56);
         else if ((active0 & 0x2000000000000000L) != 0L)
            return jjStopAtPos(1, 61);
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000000000L, active1, 0L, active2, 0L);
      case 64:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStopAtPos(1, 38);
         else if ((active0 & 0x8000000000L) != 0L)
            return jjStopAtPos(1, 39);
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0xffffe00000000000L, active2, 0x1ffffffL);
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x800000L, active2, 0L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x1000000L, active2, 0L);
      case 93:
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 41;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000L, active1, 0L, active2, 0L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x40000L, active2, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x40404032000L, active2, 0L);
      case 102:
         if ((active1 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(1, 4, 1);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x900004000L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0xc000000000L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x98100000L, active2, 0L);
      case 110:
         if ((active1 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(1, 4, 1);
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x13002208000L, active2, 0L);
      case 111:
         if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(1, 4, 1);
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x80200080000L, active2, 0L);
      case 114:
         if ((active1 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 4, 1);
         break;
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x400000L, active2, 0x2000000L);
      case 124:
         if ((active1 & 0x400L) != 0L)
         {
            jjmatchedKind = 74;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L, active1, 0L, active2, 0L);
      case 126:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStopAtPos(1, 50);
         else if ((active0 & 0x8000000000000L) != 0L)
            return jjStopAtPos(1, 51);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(0, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1, active2);
      return 2;
   }
   switch(curChar)
   {
      case 33:
         return jjMoveStringLiteralDfa3_0(active0, 0x8L, active1, 0L, active2, 0L);
      case 35:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0xffffe00000000000L, active2, 0x1ffffffL);
      case 46:
         if ((active1 & 0x2L) != 0L)
            return jjStopAtPos(2, 65);
         break;
      case 61:
         if ((active0 & 0x1000000L) != 0L)
            return jjStopAtPos(2, 24);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStopAtPos(2, 27);
         else if ((active0 & 0x20000000L) != 0L)
            return jjStopAtPos(2, 29);
         else if ((active0 & 0x40000000L) != 0L)
            return jjStopAtPos(2, 30);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStopAtPos(2, 33);
         else if ((active0 & 0x40000000000L) != 0L)
            return jjStopAtPos(2, 42);
         break;
      case 62:
         if ((active0 & 0x1000000000000000L) != 0L)
            return jjStopAtPos(2, 60);
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000000000L, active1, 0L, active2, 0L);
      case 68:
         if ((active1 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(2, 4, 0);
         break;
      case 71:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x800000L, active2, 0L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x100000L, active2, 0L);
      case 100:
         if ((active1 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(2, 4, 1);
         else if ((active1 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 4, 1);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x202000000L, active2, 0L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x4800004000L, active2, 0L);
      case 102:
         if ((active1 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x10000L, active2, 0L);
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x20000L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x108000000L, active2, 0L);
      case 108:
         if ((active1 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 4, 1);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x1000002000L, active2, 0L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x400000L, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0L, active2, 0x2000000L);
      case 114:
         if ((active1 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(2, 4, 1);
         break;
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x94048000L, active2, 0L);
      case 116:
         if ((active1 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 4, 1);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x42000000000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(1, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1, active2);
      return 3;
   }
   switch(curChar)
   {
      case 33:
         return jjMoveStringLiteralDfa4_0(active0, 0x8L, active1, 0L, active2, 0L);
      case 61:
         if ((active0 & 0x800000000000000L) != 0L)
            return jjStopAtPos(3, 59);
         break;
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x800000L, active2, 0L);
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x8000000L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x4000000L, active2, 0L);
      case 101:
         if ((active1 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(3, 4, 1);
         else if ((active1 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(3, 4, 1);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0xffffe01002400000L, active2, 0x3ffffffL);
      case 102:
         if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(3, 4, 1);
         break;
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x2080030000L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x4100000000L, active2, 0L);
      case 110:
         if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(3, 4, 1);
         else if ((active1 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(3, 4, 1);
         break;
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x100000L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x40200008000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(2, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1, active2);
      return 4;
   }
   switch(curChar)
   {
      case 33:
         return jjMoveStringLiteralDfa5_0(active0, 0x8L, active1, 0L, active2, 0L);
      case 49:
         if ((active1 & 0x200000000000L) != 0L)
         {
            jjmatchedKind = 109;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0xffc0000000000000L, active2, 0L);
      case 50:
         if ((active1 & 0x400000000000L) != 0L)
         {
            jjmatchedKind = 110;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0L, active2, 0x3ffL);
      case 51:
         if ((active1 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 111;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0L, active2, 0xffc00L);
      case 52:
         if ((active1 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 112;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0L, active2, 0x1f00000L);
      case 53:
         if ((active1 & 0x2000000000000L) != 0L)
            return jjStopAtPos(4, 113);
         break;
      case 54:
         if ((active1 & 0x4000000000000L) != 0L)
            return jjStopAtPos(4, 114);
         break;
      case 55:
         if ((active1 & 0x8000000000000L) != 0L)
            return jjStopAtPos(4, 115);
         break;
      case 56:
         if ((active1 & 0x10000000000000L) != 0L)
            return jjStopAtPos(4, 116);
         break;
      case 57:
         if ((active1 & 0x20000000000000L) != 0L)
            return jjStopAtPos(4, 117);
         break;
      case 78:
         if ((active1 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(4, 4, 0);
         break;
      case 100:
         if ((active1 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 4, 1);
         break;
      case 101:
         if ((active1 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(4, 4, 1);
         break;
      case 102:
         if ((active1 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(4, 4, 1);
         else if ((active1 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(4, 4, 1);
         break;
      case 108:
         if ((active1 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 4, 1);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x200000000L, active2, 0L);
      case 110:
         if ((active1 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(4, 4, 1);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x10000L, active2, 0L);
      case 114:
         if ((active2 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(4, 4, 1);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x40000408000L, active2, 0L);
      case 115:
         if ((active1 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(4, 4, 1);
         else if ((active1 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 4, 1);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x1000000000L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x4000000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(3, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1, active2);
      return 5;
   }
   switch(curChar)
   {
      case 33:
         return jjMoveStringLiteralDfa6_0(active0, 0x8L, active1, 0L, active2, 0L);
      case 48:
         if ((active1 & 0x40000000000000L) != 0L)
            return jjStopAtPos(5, 118);
         else if ((active2 & 0x1L) != 0L)
            return jjStopAtPos(5, 128);
         else if ((active2 & 0x400L) != 0L)
            return jjStopAtPos(5, 138);
         else if ((active2 & 0x100000L) != 0L)
            return jjStopAtPos(5, 148);
         break;
      case 49:
         if ((active1 & 0x80000000000000L) != 0L)
            return jjStopAtPos(5, 119);
         else if ((active2 & 0x2L) != 0L)
            return jjStopAtPos(5, 129);
         else if ((active2 & 0x800L) != 0L)
            return jjStopAtPos(5, 139);
         else if ((active2 & 0x200000L) != 0L)
            return jjStopAtPos(5, 149);
         break;
      case 50:
         if ((active1 & 0x100000000000000L) != 0L)
            return jjStopAtPos(5, 120);
         else if ((active2 & 0x4L) != 0L)
            return jjStopAtPos(5, 130);
         else if ((active2 & 0x1000L) != 0L)
            return jjStopAtPos(5, 140);
         else if ((active2 & 0x400000L) != 0L)
            return jjStopAtPos(5, 150);
         break;
      case 51:
         if ((active1 & 0x200000000000000L) != 0L)
            return jjStopAtPos(5, 121);
         else if ((active2 & 0x8L) != 0L)
            return jjStopAtPos(5, 131);
         else if ((active2 & 0x2000L) != 0L)
            return jjStopAtPos(5, 141);
         else if ((active2 & 0x800000L) != 0L)
            return jjStopAtPos(5, 151);
         break;
      case 52:
         if ((active1 & 0x400000000000000L) != 0L)
            return jjStopAtPos(5, 122);
         else if ((active2 & 0x10L) != 0L)
            return jjStopAtPos(5, 132);
         else if ((active2 & 0x4000L) != 0L)
            return jjStopAtPos(5, 142);
         else if ((active2 & 0x1000000L) != 0L)
            return jjStopAtPos(5, 152);
         break;
      case 53:
         if ((active1 & 0x800000000000000L) != 0L)
            return jjStopAtPos(5, 123);
         else if ((active2 & 0x20L) != 0L)
            return jjStopAtPos(5, 133);
         else if ((active2 & 0x8000L) != 0L)
            return jjStopAtPos(5, 143);
         break;
      case 54:
         if ((active1 & 0x1000000000000000L) != 0L)
            return jjStopAtPos(5, 124);
         else if ((active2 & 0x40L) != 0L)
            return jjStopAtPos(5, 134);
         else if ((active2 & 0x10000L) != 0L)
            return jjStopAtPos(5, 144);
         break;
      case 55:
         if ((active1 & 0x2000000000000000L) != 0L)
            return jjStopAtPos(5, 125);
         else if ((active2 & 0x80L) != 0L)
            return jjStopAtPos(5, 135);
         else if ((active2 & 0x20000L) != 0L)
            return jjStopAtPos(5, 145);
         break;
      case 56:
         if ((active1 & 0x4000000000000000L) != 0L)
            return jjStopAtPos(5, 126);
         else if ((active2 & 0x100L) != 0L)
            return jjStopAtPos(5, 136);
         else if ((active2 & 0x40000L) != 0L)
            return jjStopAtPos(5, 146);
         break;
      case 57:
         if ((active1 & 0x8000000000000000L) != 0L)
            return jjStopAtPos(5, 127);
         else if ((active2 & 0x200L) != 0L)
            return jjStopAtPos(5, 137);
         else if ((active2 & 0x80000L) != 0L)
            return jjStopAtPos(5, 147);
         break;
      case 101:
         if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(5, 4, 1);
         else if ((active1 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(5, 4, 1);
         else if ((active1 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(5, 4, 1);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x10000L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x400000L, active2, 0L);
      case 110:
         if ((active1 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 4, 1);
         break;
      case 115:
         if ((active1 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 4, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(4, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 33:
         return jjMoveStringLiteralDfa7_0(active0, 0x8L, active1, 0L);
      case 99:
         if ((active1 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(6, 4, 1);
         break;
      case 100:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x10000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1, 0L);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 33:
         return jjMoveStringLiteralDfa8_0(active0, 0x8L, active1, 0L);
      case 63:
         if ((active1 & 0x10000L) != 0L)
            return jjStopAtPos(7, 80);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1, 0L);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, 0L, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 33:
         return jjMoveStringLiteralDfa9_0(active0, 0x8L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, 0L, 0L);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, 0L, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 33:
         if ((active0 & 0x8L) != 0L)
            return jjStopAtPos(9, 3);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0, 0L, 0L);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 10;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 5)
                        kind = 5;
                     jjCheckNAdd(3);
                  }
                  else if ((0x800000000000400L & l) != 0L)
                  {
                     if (kind > 13)
                        kind = 13;
                  }
                  else if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 3:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  kind = 5;
                  jjCheckNAdd(3);
                  break;
               case 4:
                  if ((0x800000000000400L & l) != 0L)
                     kind = 13;
                  break;
               case 5:
                  if (curChar == 62)
                     kind = 13;
                  break;
               case 9:
                  if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 4)
                        kind = 4;
                     jjCheckNAdd(1);
                  }
                  else if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 4)
                        kind = 4;
                     jjCheckNAdd(0);
                  }
                  else if (curChar == 95)
                  {
                     if (kind > 4)
                        kind = 4;
                  }
                  break;
               case 0:
                  if ((0x7fffffeL & l) == 0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAdd(0);
                  break;
               case 1:
                  if ((0x7fffffe00000000L & l) == 0L)
                     break;
                  kind = 4;
                  jjCheckNAdd(1);
                  break;
               case 6:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 7:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 10 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, "\41\41\41\41\41\41\41\41\41\41", null, null, "\121", "\161", 
"\170", "\162", "\151", "\157", "\160", null, "\174", "\42", "\47", "\140", "\72", 
"\75", "\53\75", "\52\75", "\57\75", "\45\75", "\52\52\75", "\55\75", "\46\75", 
"\46\46\75", "\174\75", "\174\174\75", "\74\74\75", "\136\75", "\75\75", "\75\75\75", 
"\173", "\175", "\100", "\44", "\53\100", "\55\100", "\133", "\133\135", 
"\133\135\75", "\135", "\50", "\51", "\54", "\41", "\77", "\41\75", "\41\176", "\75\176", 
"\176", "\74", "\74\74", "\76", "\76\76", "\74\75", "\76\75", "\40\76\76\75", 
"\74\75\76", "\75\76", "\136", "\56", "\56\56", "\56\56\56", "\53", "\55", "\52", "\52\52", 
"\57", "\45", "\46", "\46\46", "\174\174", "\72\72", "\144\157", "\163\145\154\146", 
"\164\150\145\156", "\145\156\163\165\162\145", "\144\145\146\151\156\145\144\77", 
"\142\145\147\151\156", "\143\141\163\145", "\146\157\162", "\143\154\141\163\163", "\145\156\144", 
"\156\165\155\145\162\151\143", "\102\105\107\111\116", "\105\116\104", "\165\156\144\145\146", 
"\162\145\163\143\165\145", "\141\154\151\141\163", "\145\154\163\145", "\151\146", "\151\156", 
"\145\154\163\151\146", "\167\150\151\154\145", "\155\157\144\165\154\145", "\144\145\146", 
"\167\150\145\156", "\165\156\154\145\163\163", "\165\156\164\151\154", "\171\151\145\154\144", 
"\156\151\154", "\141\156\144", "\157\162", "\162\145\164\165\162\156", "\156\157\164", null, 
"\41\100\43\145\61", "\41\100\43\145\62", "\41\100\43\145\63", "\41\100\43\145\64", 
"\41\100\43\145\65", "\41\100\43\145\66", "\41\100\43\145\67", "\41\100\43\145\70", 
"\41\100\43\145\71", "\41\100\43\145\61\60", "\41\100\43\145\61\61", "\41\100\43\145\61\62", 
"\41\100\43\145\61\63", "\41\100\43\145\61\64", "\41\100\43\145\61\65", "\41\100\43\145\61\66", 
"\41\100\43\145\61\67", "\41\100\43\145\61\70", "\41\100\43\145\61\71", "\41\100\43\145\62\60", 
"\41\100\43\145\62\61", "\41\100\43\145\62\62", "\41\100\43\145\62\63", "\41\100\43\145\62\64", 
"\41\100\43\145\62\65", "\41\100\43\145\62\66", "\41\100\43\145\62\67", "\41\100\43\145\62\70", 
"\41\100\43\145\62\71", "\41\100\43\145\63\60", "\41\100\43\145\63\61", "\41\100\43\145\63\62", 
"\41\100\43\145\63\63", "\41\100\43\145\63\64", "\41\100\43\145\63\65", "\41\100\43\145\63\66", 
"\41\100\43\145\63\67", "\41\100\43\145\63\70", "\41\100\43\145\63\71", "\41\100\43\145\64\60", 
"\41\100\43\145\64\61", "\41\100\43\145\64\62", "\41\100\43\145\64\63", "\41\100\43\145\64\64", 
"\163\165\160\145\162", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xfffffffffffffff9L, 0xffffffffffffffffL, 0x3ffffffL, 
};
static final long[] jjtoSkip = {
   0x6L, 0x0L, 0x0L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[10];
static private final int[] jjstateSet = new int[20];
private static final StringBuilder jjimage = new StringBuilder();
private static StringBuilder image = jjimage;
private static int jjimageLen;
private static int lengthOfMatch;
static protected char curChar;
/** Constructor. */
public RubyParser14TokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public RubyParser14TokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 10; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   if (jjmatchedPos < 0)
   {
      if (image == null)
         curTokenImage = "";
      else
         curTokenImage = image.toString();
      beginLine = endLine = input_stream.getBeginLine();
      beginColumn = endColumn = input_stream.getBeginColumn();
   }
   else
   {
      String im = jjstrLiteralImages[jjmatchedKind];
      curTokenImage = (im == null) ? input_stream.GetImage() : im;
      beginLine = input_stream.getBeginLine();
      beginColumn = input_stream.getBeginColumn();
      endLine = input_stream.getEndLine();
      endColumn = input_stream.getEndColumn();
   }
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   try { input_stream.backup(0);
      while (curChar <= 9 && (0x200L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 108;
   jjmatchedPos = -1;
   curPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         TokenLexicalActions(matchedToken);
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static int[] jjemptyLineNo = new int[1];
static int[] jjemptyColNo = new int[1];
static boolean[] jjbeenHere = new boolean[1];
static void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 0 :
         break;
      case 3 :
         break;
      case 4 :
         break;
      case 5 :
         break;
      case 6 :
         break;
      case 7 :
         break;
      case 8 :
         break;
      case 9 :
         break;
      case 10 :
         break;
      case 11 :
         break;
      case 12 :
         break;
      case 13 :
         break;
      case 14 :
         break;
      case 15 :
         break;
      case 16 :
         break;
      case 17 :
         break;
      case 18 :
         break;
      case 19 :
         break;
      case 20 :
         break;
      case 21 :
         break;
      case 22 :
         break;
      case 23 :
         break;
      case 24 :
         break;
      case 25 :
         break;
      case 26 :
         break;
      case 27 :
         break;
      case 28 :
         break;
      case 29 :
         break;
      case 30 :
         break;
      case 31 :
         break;
      case 32 :
         break;
      case 33 :
         break;
      case 34 :
         break;
      case 35 :
         break;
      case 36 :
         break;
      case 37 :
         break;
      case 38 :
         break;
      case 39 :
         break;
      case 40 :
         break;
      case 41 :
         break;
      case 42 :
         break;
      case 43 :
         break;
      case 44 :
         break;
      case 45 :
         break;
      case 46 :
         break;
      case 47 :
         break;
      case 48 :
         break;
      case 49 :
         break;
      case 50 :
         break;
      case 51 :
         break;
      case 52 :
         break;
      case 53 :
         break;
      case 54 :
         break;
      case 55 :
         break;
      case 56 :
         break;
      case 57 :
         break;
      case 58 :
         break;
      case 59 :
         break;
      case 60 :
         break;
      case 61 :
         break;
      case 62 :
         break;
      case 63 :
         break;
      case 64 :
         break;
      case 65 :
         break;
      case 66 :
         break;
      case 67 :
         break;
      case 68 :
         break;
      case 69 :
         break;
      case 70 :
         break;
      case 71 :
         break;
      case 72 :
         break;
      case 73 :
         break;
      case 74 :
         break;
      case 75 :
         break;
      case 76 :
         break;
      case 77 :
         break;
      case 78 :
         break;
      case 79 :
         break;
      case 80 :
         break;
      case 81 :
         break;
      case 82 :
         break;
      case 83 :
         break;
      case 84 :
         break;
      case 85 :
         break;
      case 86 :
         break;
      case 87 :
         break;
      case 88 :
         break;
      case 89 :
         break;
      case 90 :
         break;
      case 91 :
         break;
      case 92 :
         break;
      case 93 :
         break;
      case 94 :
         break;
      case 95 :
         break;
      case 96 :
         break;
      case 97 :
         break;
      case 98 :
         break;
      case 99 :
         break;
      case 100 :
         break;
      case 101 :
         break;
      case 102 :
         break;
      case 103 :
         break;
      case 104 :
         break;
      case 105 :
         break;
      case 106 :
         break;
      case 107 :
         break;
      case 108 :
         if (jjmatchedPos == -1)
         {
            if (jjbeenHere[0] &&
                jjemptyLineNo[0] == input_stream.getBeginLine() &&
                jjemptyColNo[0] == input_stream.getBeginColumn())
               throw new TokenMgrError(("Error: Bailing out of infinite loop caused by repeated empty string matches at line " + input_stream.getBeginLine() + ", column " + input_stream.getBeginColumn() + "."), TokenMgrError.LOOP_DETECTED);
            jjemptyLineNo[0] = input_stream.getBeginLine();
            jjemptyColNo[0] = input_stream.getBeginColumn();
            jjbeenHere[0] = true;
         }
         break;
      case 109 :
         break;
      case 110 :
         break;
      case 111 :
         break;
      case 112 :
         break;
      case 113 :
         break;
      case 114 :
         break;
      case 115 :
         break;
      case 116 :
         break;
      case 117 :
         break;
      case 118 :
         break;
      case 119 :
         break;
      case 120 :
         break;
      case 121 :
         break;
      case 122 :
         break;
      case 123 :
         break;
      case 124 :
         break;
      case 125 :
         break;
      case 126 :
         break;
      case 127 :
         break;
      case 128 :
         break;
      case 129 :
         break;
      case 130 :
         break;
      case 131 :
         break;
      case 132 :
         break;
      case 133 :
         break;
      case 134 :
         break;
      case 135 :
         break;
      case 136 :
         break;
      case 137 :
         break;
      case 138 :
         break;
      case 139 :
         break;
      case 140 :
         break;
      case 141 :
         break;
      case 142 :
         break;
      case 143 :
         break;
      case 144 :
         break;
      case 145 :
         break;
      case 146 :
         break;
      case 147 :
         break;
      case 148 :
         break;
      case 149 :
         break;
      case 150 :
         break;
      case 151 :
         break;
      case 152 :
         break;
      case 153 :
         break;
      default :
         break;
   }
}
static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

}
