/* Generated By:JavaCC: Do not edit this line. RbParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RbParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T = 3;
  /** RegularExpression Id. */
  int clazz = 4;
  /** RegularExpression Id. */
  int symbol = 5;
  /** RegularExpression Id. */
  int letter = 6;
  /** RegularExpression Id. */
  int digit = 7;
  /** RegularExpression Id. */
  int op_asgn = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<T>",
    "\"class\"",
    "<symbol>",
    "<letter>",
    "<digit>",
    "<op_asgn>",
  };

}
